# Generated by Django 6.0.7 on 2026-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Deskless', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('color', models.CharField(default='#1f2937', help_text='Header/rail color', max_length=7)),
                ('accent', models.CharField(default='#2563eb', help_text='Buttons & links', max_length=7)),
            ],
            options={
                'verbose_name': 'Organization settings',
                'verbose_name_plural': 'Organization settings',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('event', models.CharField(choices=[('ticket.created', 'Ticket created'), ('ticket.closed', 'Ticket closed')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='related',
            field=models.ManyToManyField(blank=True, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, help_text='How this ticket was resolved'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=12),
        ),
    ]
