# Generated by Django 6.0.7 on 2026-07-17 09:10

from django.db import migrations


def resolved_to_closed(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    Ticket.objects.filter(status='resolved').update(status='closed')


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_orgsettings_webhook_ticket_related_ticket_resolution_and_more'),
    ]

    operations = [
        migrations.RunPython(resolved_to_closed, migrations.RunPython.noop),
    ]
