# Generated by Django 6.0.7 on 2026-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_migrate_resolved_to_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='sla_high',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='sla_low',
            field=models.PositiveIntegerField(default=72),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='sla_normal',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='sla_urgent',
            field=models.PositiveIntegerField(default=4, help_text='Hours to resolve urgent'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='breach_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
    ]
