# Generated by Django 6.0.7 on 2026-07-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_cannedreply_category_tag_attachment_ticket_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='business_days',
            field=models.CharField(default='0,1,2,3,4', help_text='Working weekdays, comma-separated (Mon=0 … Sun=6)', max_length=13),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='business_end',
            field=models.PositiveSmallIntegerField(default=17, help_text='Work day end hour (0-23)'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='business_hours_enabled',
            field=models.BooleanField(default=False, help_text='Count SLA only during business hours'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='business_start',
            field=models.PositiveSmallIntegerField(default=9, help_text='Work day start hour (0-23)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='csat_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='csat_token',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('body', models.TextField(help_text='Plain text or basic HTML')),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='tickets.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
