# Generated by Django 6.0.7 on 2026-07-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_orgsettings_business_days_orgsettings_business_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='holidays',
            field=models.TextField(blank=True, help_text='Holiday dates (YYYY-MM-DD), one per line — excluded from SLA'),
        ),
    ]
