# Generated by Django 6.0.7 on 2026-07-19 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_orgsettings_holidays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='ticket_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.group'),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keyword', models.CharField(help_text='Case-insensitive text to match in subject or body', max_length=100)),
                ('set_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], help_text='Optionally force a priority', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('set_group', models.ForeignKey(blank=True, help_text='Assign matching tickets to this group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
