# Generated by Django 6.0.7 on 2026-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_group_ticket_group_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('escalated', 'Escalate'), ('closed', 'Closed')], default='open', max_length=12),
        ),
    ]
