# Generated by Django 6.0.7 on 2026-07-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_paused_at_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='reopen_days',
            field=models.PositiveIntegerField(default=3, help_text='Days a customer can reopen a closed ticket (0 disables)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10)),
                ('hours', models.PositiveIntegerField(help_text='Hours to resolve')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='tickets.category')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='tickets.group')),
            ],
            options={
                'verbose_name_plural': 'SLA policies',
                'ordering': ['group__name', 'category__name', 'priority'],
            },
        ),
    ]
