# Generated by Django 6.0.7 on 2026-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_orgsettings_reopen_days_ticket_closed_at_slapolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='email_from',
            field=models.EmailField(blank=True, help_text='From address (defaults to SMTP user)', max_length=254),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP server', max_length=200),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='email_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='email_user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='site_url',
            field=models.URLField(blank=True, help_text='Public base URL, e.g. https://deskless.example.com — used in email links'),
        ),
    ]
